# Generated by Django 5.0.2 on 2024-06-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_user_about_me_user_birthday_user_favorite_song_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='uploads/user.png', upload_to='uploads/avatars/'),
        ),
    ]
