# Generated by Django 5.0.2 on 2024-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
