# Generated by Django 5.0.2 on 2024-07-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_bed_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
